version: '3'

services:

  database:
    image: mariadb
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: always
    networks:
      - wordpress-internal
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_ROOT_PASSWORD: db_password
    volumes:
      - ./database:/var/lib/mysql

  php:
    build: .
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_bedrock
    depends_on:
      - database
    links:
      - database
    networks:
      - traefikify
      - wordpress-internal
    environment:
      DB_HOST: database
      DB_NAME: db_name
      DB_USER: root
      DB_PASSWORD: db_password
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
    volumes:
      - ./:/code
      - ./config/docker/php.ini:/usr/local/etc/php/conf.d/bedrock.ini

  wordpress:
    image: nginx
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    depends_on:
      - php
    links:
      - php
    networks:
      - traefikify
      - wordpress-internal
    labels:
      traefik.backend: "${DOMAIN_CURRENT_SITE}"
      traefik.docker.network: "traefikify"
      traefik.frontend.rule: "Host:${DOMAIN_CURRENT_SITE}"
      traefik.enable: "true"
      traefik.port: "80"
    volumes:
      - ./:/code
      - ./config/docker/site.nginx.conf:/etc/nginx/conf.d/site.nginx.conf

networks:
  traefikify:
    external: true
  wordpress-internal:
    external: false