---
- name: Generate self-signed certificates
  shell: "openssl req -new -newkey rsa:2048 \
    -days 3650 -nodes -x509 -sha256 \
    -extensions req_ext -config <( \
cat <<' EOF'\n
[req]\n
prompt = no\n
distinguished_name = req_dn\n
[req_dn]\n
commonName = {{ item.value.site_hosts[0].canonical }}\n
[req_ext]\n
subjectAltName = {{ site_hosts | union(multisite_subdomains_wildcards) | map('regex_replace', '(.*)', 'DNS:\\1') | join(',') }}\n
EOF\n
    ) \
    -keyout {{ item.key | quote }}.key -out {{ item.key | quote }}.cert"
  args:
    executable: "/bin/bash"
    chdir: "{{ nginx_ssl_path }}"
    creates: "{{ item.key }}.*"
  with_dict: "{{ wordpress_sites | combine(ssl_default_site) }}"
  when:
    - sites_use_ssl
    - ssl_enabled
    - item.value.ssl.provider | default('manual') == 'self-signed'
  notify: reload nginx
