---
- include_tasks: "{{ include_path }}"
  with_items: "{{ deploy_before | default([]) }}"
  loop_control:
    loop_var: include_path
  tags: deploy-before

- import_tasks: initialize.yml
- import_tasks: update.yml
- import_tasks: prepare.yml
- import_tasks: build.yml
- import_tasks: share.yml
- import_tasks: finalize.yml

- include_tasks: "{{ include_path }}"
  with_items: "{{ deploy_after | default([]) }}"
  loop_control:
    loop_var: include_path
  tags: deploy-after
