---
- include_tasks: "{{ include_path }}"
  with_items: "{{ deploy_prepare_before | default([]) }}"
  loop_control:
    loop_var: include_path
  tags: deploy-prepare-before

- name: write unfinished file
  file:
    path: "{{ project_source_path }}/{{ deploy_helper.unfinished_filename }}"
    state: touch

- name: Check for project repo subtree
  stat:
    path: "{{ project_source_path }}/{{ project.repo_subtree_path }}"
  register: project_subtree_full_path
  when: project.repo_subtree_path is defined

- name: Fail if repo_subtree_path is set incorrectly
  fail:
    msg: "repo subtree is set to '{{ project.repo_subtree_path }}' but that path does not exist in the repo. Edit `repo_subtree_path` for '{{ site }}' in `wordpress_sites.yml`."
  when: project.repo_subtree_path is defined and not project_subtree_full_path.stat.exists

- name: Create new release dir
  file:
    path: "{{ deploy_helper.new_release_path }}"
    state: directory

- name: Run git archive to populate new build dir
  shell: git archive {{ project_version }} | tar xf - -C {{ deploy_helper.new_release_path }}
  args:
    chdir: "{{ project_source_path }}"
  when: project.repo_subtree_path is not defined

- name: Run git archive with subdirectory to populate new build dir
  shell: git archive {{ project_version }} {{ project.repo_subtree_path }} | tar -x --strip-components {{ project.repo_subtree_path.split('/') | count }} -f - -C {{ deploy_helper.new_release_path }}
  args:
    chdir: "{{ project_source_path }}"
  when: project.repo_subtree_path is defined

- include_tasks: "{{ include_path }}"
  with_items: "{{ deploy_prepare_after | default([]) }}"
  loop_control:
    loop_var: include_path
  tags: deploy-prepare-after
