---
- name: Install memcached
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_dict: "{{ memcached_packages }}"

- name: Copy the client configuration file
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
  notify: restart memcached

- name: Set the max open file descriptors
  sysctl:
    name: fs.file-max
    value: "{{ memcached_fs_file_max }}"
    state: present

- name: Start the memcached service
  service:
    name: memcached
    state: started
    enabled: yes
