 - name: Install npm dependencies
   command: yarn
   connection: local
   args:
     chdir: "{{ project_local_path }}/web/app/themes/{{ SITE_DOMAIN }}"

 - name: Install Composer dependencies
   command: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts
   args:
     chdir: "{{ deploy_helper.new_release_path }}/web/app/themes/{{ SITE_DOMAIN }}"

 - name: Compile assets for production
   command: yarn build:production
   connection: local
   args:
     chdir: "{{ project_local_path }}/web/app/themes/{{ SITE_DOMAIN }}"

 - name: Copy production assets
   synchronize:
     src: "{{ project_local_path }}/web/app/themes/{{ SITE_DOMAIN }}/dist"
     dest: "{{ deploy_helper.new_release_path }}/web/app/themes/{{ SITE_DOMAIN }}"
     group: no
     owner: no
     rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r
