wordpress_sites:
  {{ SITE_URL }}:
    site_hosts:
      - canonical: {{ SITE_URL }}
    local_path: ../site
    repo: git@github.com:{{ GITHUB_USER }}/{{ SITE_URL }}.git
    repo_subtree_path: site
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    backup:
      enabled: true
      auto: true
      target: b2://account_id:application_key@{{ SITE_DOMAIN }}-{{ SITE_TLD }}/
      schedule: '0 0 3 * * ?'
      purge: true