language: python
python:
  - 2.7
  - 3.6
sudo: false
cache: pip
install:
  - pip install ansible
script:
  - ansible-galaxy install --force -r requirements.yml -p vendor/roles
  - ansible-playbook --syntax-check -e env=development deploy.yml
  - ansible-playbook --syntax-check -e env=development dev.yml
  - ansible-playbook --syntax-check -e env=development server.yml
