---
- name: Ensure necessary variables are defined
  hosts: localhost
  gather_facts: false
  vars:
    extra_vars_command: "{{ (playbook == 'server.yml') | ternary('env=<environment>', '\"site=<domain> env=<environment>\"') }}"
  tasks:
    - name: Ensure environment is defined
      fail:
        msg: |
          Environment missing. Use `-e` to define `env`:
          ansible-playbook {{ playbook }} -e {{ extra_vars_command }}
      when: env is not defined
      tags: [variable-check]
